### PR TITLE
Android support

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Comment by FlafyDev** [comment]
Thanks! I remember trying to run an android build of the mod and it crashed on startup. I will try your changes soon. (Assuming this PR is ready)

Also, it seems `ANSongCell::setSong()` was reverted to a few commits ago here

**Comment by TheBearodactyl** [comment]
> Thanks! I remember trying to run an android build of the mod and it crashed on startup. I will try your changes soon. (Assuming this PR is ready)
> 
> Also, it seems `ANSongCell::setSong()` was reverted to a few commits ago here

there is one problem. i just need to figure out how to make the Android specific directory if it doesn't exist. I've tried a few different ways of doing it but they've all just crashed the game :(

**Comment by TheBearodactyl** [comment]
Oki it works now

**Comment by TheBearodactyl** [comment]
@FlafyDev it's ready for merging, i solved pretty much the only problem lol

**Comment by FlafyDev** [comment]
Ok, thanks!
I'll Soon merge it to an intermediate branch so I can work on it a bit and:
- Fix the function `ANSongCell::setSong()` that seem to have been reverted to a few commits ago in this PR.
- Clean the code where I can

**Comment by TheBearodactyl** [comment]
also, I reverted the `setSong` function because Android doesn't like `try/catch`

**Comment by TheBearodactyl** [comment]
@FlafyDev I fixed the code looking bad, lemme make an android friendly version of the newer `setSong` version real quick

**Comment by TheBearodactyl** [comment]
@FlafyDev Should be good to merge now, everything is cleaned up and formatted, and the `setSong` function has been updated to the latest version with some modifications for Android (because Android doesn't like `try/catch`)

**Comment by FlafyDev** [comment]
image
oh it seems you changed the formatter settings so it left a lot of changes 
image

**Comment by TheBearodactyl** [comment]
> image oh it seems you changed the formatter settings so it left a lot of changes image
> 
> I prefer not to do that (at least not in this PR) as it obscures history. And There isn't really a need for a new formatter settings.

I can revert the formatter settings real quick, and the squashed commit has all of the changes logged in it, so that shouldn't be too much of a problem.

**Comment by TheBearodactyl** [comment]
it is done

**Comment by FlafyDev** [comment]
@TheBearodactyl 

There seem to be a lot of unnecessary changes(like the Rust like types). And some formatting issues. I reverted these back. Is it correct that these are all the necessary changes for android support?

```patch
diff --git a/.github/workflows/multi-platform.yml b/.github/workflows/multi-platform.yml
index 01d6d83..d6172ef 100644
--- a/.github/workflows/multi-platform.yml
+++ b/.github/workflows/multi-platform.yml
@@ -18,13 +18,13 @@ jobs:
         # - name: macOS
         #   os: macos-latest
 
-        # - name: Android32
-        #   os: ubuntu-latest
-        #   target: Android32
-        #
-        # - name: Android64
-        #   os: ubuntu-latest
-        #   target: Android64
+        - name: Android32
+          os: ubuntu-latest
+          target: Android32
+
+        - name: Android64
+          os: ubuntu-latest
+          target: Android64
 
     name: ${{ matrix.config.name }}
     runs-on: ${{ matrix.config.os }}
diff --git a/mod.json b/mod.json
index df955d3..df9ecb5 100644
--- a/mod.json
+++ b/mod.json
@@ -1,6 +1,9 @@
 {
 	"geode": "2.0.0-beta.27",
-	"gd": "2.204",
+	"gd": {
+		"win": "2.204",
+		"android": "2.205"
+	},
 	"version": "v0.0.3",
 	"id": "flafy.autonong",
 	"name": "Auto Nong",
diff --git a/src/ui/an_song_cell.cpp b/src/ui/an_song_cell.cpp
index b3e9dfa..eed58f9 100644
--- a/src/ui/an_song_cell.cpp
+++ b/src/ui/an_song_cell.cpp
@@ -143,21 +143,29 @@ void ANSongCell::setSong() {
 }
 
 fs::path ANSongCell::getFileDownloadPath(bool create) {
+#ifdef GEODE_IS_ANDROID
+  std::string baseDir = "/storage/emulated/0/nongs";
+  if (!fs::exists(baseDir)) {
+    fs::create_directories(baseDir);
+  }
+#else
+  std::string baseDir = Mod::get()->getSaveDir().string();
+#endif
+
   if (typeid(*m_anSong) == typeid(ANYTSong)) {
     const ANYTSong *ytSong = static_cast<ANYTSong *>(m_anSong);
     const std::string videoId = ytSong->m_ytId;
     if (create) {
-      fs::create_directory(fmt::format("{}\\youtube", Mod::get()->getSaveDir().string()));
+      fs::create_directories(fmt::format("{}/youtube", baseDir));
     }
-    return fmt::format("{}\\youtube\\{}.mp3", Mod::get()->getSaveDir().string(), videoId);
+    return fmt::format("{}/youtube/{}.mp3", baseDir, videoId);
   }
   if (typeid(*m_anSong) == typeid(ANHostSong)) {
     const ANHostSong *hostSong = static_cast<ANHostSong *>(m_anSong);
     if (create) {
-      fs::create_directory(fmt::format("{}\\host", Mod::get()->getSaveDir().string()));
+      fs::create_directories(fmt::format("{}/host", baseDir));
     }
-    return fmt::format("{}\\host\\{}.mp3", Mod::get()->getSaveDir().string(),
-                       urlToFilename(hostSong->m_url));
+    return fmt::format("{}/host/{}.mp3", baseDir, urlToFilename(hostSong->m_url));
   }
   return "";
 }
```

Also, I tested your version but I'm crashing on startup when trying to decompress the indexes. Are you not crashing there?

I used an index that doesn't require decompression and managed to get in. I opened the auto nong menu and got another crash. This time there was a crashlog and after reading it it seems to crash on 

```
create_directories: Permission denied ["/storage/emulated/0/nongs"]
``

Are you not experiencing any of these crashes?

**Comment by TheBearodactyl** [comment]
> @TheBearodactyl
> 
> There seem to be a lot of unnecessary changes(like the Rust like types). And some formatting issues. I reverted these back. Is it correct that these are all the necessary changes for android support?
> 
> ```diff
> diff --git a/.github/workflows/multi-platform.yml b/.github/workflows/multi-platform.yml
> index 01d6d83..d6172ef 100644
> --- a/.github/workflows/multi-platform.yml
> +++ b/.github/workflows/multi-platform.yml
> @@ -18,13 +18,13 @@ jobs:
>          # - name: macOS
>          #   os: macos-latest
>  
> -        # - name: Android32
> -        #   os: ubuntu-latest
> -        #   target: Android32
> -        #
> -        # - name: Android64
> -        #   os: ubuntu-latest
> -        #   target: Android64
> +        - name: Android32
> +          os: ubuntu-latest
> +          target: Android32
> +
> +        - name: Android64
> +          os: ubuntu-latest
> +          target: Android64
>  
>      name: ${{ matrix.config.name }}
>      runs-on: ${{ matrix.config.os }}
> diff --git a/mod.json b/mod.json
> index df955d3..df9ecb5 100644
> --- a/mod.json
> +++ b/mod.json
> @@ -1,6 +1,9 @@
>  {
>  	"geode": "2.0.0-beta.27",
> -	"gd": "2.204",
> +	"gd": {
> +		"win": "2.204",
> +		"android": "2.205"
> +	},
>  	"version": "v0.0.3",
>  	"id": "flafy.autonong",
>  	"name": "Auto Nong",
> diff --git a/src/ui/an_song_cell.cpp b/src/ui/an_song_cell.cpp
> index b3e9dfa..eed58f9 100644
> --- a/src/ui/an_song_cell.cpp
> +++ b/src/ui/an_song_cell.cpp
> @@ -143,21 +143,29 @@ void ANSongCell::setSong() {
>  }
>  
>  fs::path ANSongCell::getFileDownloadPath(bool create) {
> +#ifdef GEODE_IS_ANDROID
> +  std::string baseDir = "/storage/emulated/0/nongs";
> +  if (!fs::exists(baseDir)) {
> +    fs::create_directories(baseDir);
> +  }
> +#else
> +  std::string baseDir = Mod::get()->getSaveDir().string();
> +#endif
> +
>    if (typeid(*m_anSong) == typeid(ANYTSong)) {
>      const ANYTSong *ytSong = static_cast<ANYTSong *>(m_anSong);
>      const std::string videoId = ytSong->m_ytId;
>      if (create) {
> -      fs::create_directory(fmt::format("{}\\youtube", Mod::get()->getSaveDir().string()));
> +      fs::create_directories(fmt::format("{}/youtube", baseDir));
>      }
> -    return fmt::format("{}\\youtube\\{}.mp3", Mod::get()->getSaveDir().string(), videoId);
> +    return fmt::format("{}/youtube/{}.mp3", baseDir, videoId);
>    }
>    if (typeid(*m_anSong) == typeid(ANHostSong)) {
>      const ANHostSong *hostSong = static_cast<ANHostSong *>(m_anSong);
>      if (create) {
> -      fs::create_directory(fmt::format("{}\\host", Mod::get()->getSaveDir().string()));
> +      fs::create_directories(fmt::format("{}/host", baseDir));
>      }
> -    return fmt::format("{}\\host\\{}.mp3", Mod::get()->getSaveDir().string(),
> -                       urlToFilename(hostSong->m_url));
> +    return fmt::format("{}/host/{}.mp3", baseDir, urlToFilename(hostSong->m_url));
>    }
>    return "";
>  }
> ```
> 
> Also, I tested your version but I'm crashing on startup when trying to decompress the indexes. Are you not crashing there?
> 
> I used an index that doesn't require decompression and managed to get in. I opened the auto nong menu and got another crash. This time there was a crashlog and after reading it it seems to crash on
> 
> ```
> create_directories: Permission denied ["/storage/emulated/0/nongs"]
> ```
> 
> Are you not experiencing any of these crashes?

yes, in the action, uncommenting the thingies makes the github actions build for android. also, the changes in the paths make it android compatible since android paths use forward slashes, and `\` is used for escaping characters in linux devices (which android is). Also, no i haven't had any of those crashes. I added the `create_directories` thingy because the game crashes if the android specific directory doesn't already exist.

**Comment by FlafyDev** [comment]
I don't know how you had permission to write in `/storage/emulated/0/nongs` (Maybe another mod asked for perms and GD still had it). But changing back to 
```cpp
  std::string baseDir = Mod::get()->getSaveDir().string();
```
for Android as well made it work for me.

There is still the issue with the decompression, though. Not sure how to solve it. But everything else seem to work on both Android and Windows :D

**Comment by TheBearodactyl** [comment]
> I don't know how you had permission to write in `/storage/emulated/0/nongs` (Maybe another mod asked for perms and GD still had it). But changing back to
> 
> ```c++
>   std::string baseDir = Mod::get()->getSaveDir().string();
> ```
> 
> for Android as well made it work for me.
> 
> There is still the issue with the decompression, though. Not sure how to solve it. But everything else seem to work on both Android and Windows :D

try setting the nong for a song with that, it won't work. also, you have to give the geode launcher filesystem perms in the app settings lol

**Comment by FlafyDev** [comment]
> @FlafyDev try setting the nong for a song with that, it won't work. also, you have to give the geode launcher filesystem perms in the app settings lol

Setting the song through auto-nong still works. 

This is also what jukebox does
https://github.com/Fleeym/jukebox/blob/035e7c5f2f237c978cfac294c8b4b56cfc7fbaa5/src/managers/nong_manager.cpp#L326
and jukebox works on android just fine

**Comment by FlafyDev** [comment]
oh nevermind, it's not due to the decompression step. But these work for me:

https://cdn.jsdelivr.net/gh/FlafyDev/auto-nong-indexes@dist/official.json.gz 
https://raw.githubusercontent.com/FlafyDev/auto-nong-indexes/main/official.json

these crash the game:

https://raw.githubusercontent.com/FlafyDev/auto-nong-indexes/dist/sfh-rooot.json.gz
https://raw.githubusercontent.com/FlafyDev/auto-nong-indexes/dist/sfh-yt.json.gz
https://cdn.jsdelivr.net/gh/FlafyDev/auto-nong-indexes@dist/sfh-rooot.json.gz

It's probably something in the contents of the file

**Comment by FlafyDev** [comment]
Figured it out. for some reason it takes time for my android device to decompress the entire json, but the code still continues...  for smaller json files like `official` it manages to complete it before the next line uses the string. but for bigger files like sfh-rooot.json.gz it crashes.

I'll make a 1 second loop that checks if the string is empty.

**Pull request merged**
