### PR TITLE
Update cobalt API

### PR DESCRIPTION
**Pull request by larziwau**
Updates the cobalt API.

### CODE REVIEW

**Comment by larziwau** [comment]
Well ive did read some issues and cobalt is gonna drop supporting apis. We need to host our own runner? Any ideas for this @RoootTheFox

**Comment by RoootTheFox** [comment]
> Well ive did read some issues and cobalt is gonna drop supporting apis. We need to host our own runner? Any ideas for this @RoootTheFox

I am hosting my own cobalt instance atm, although it is constantly blocked from accessing YouTube due to its anti-bot IP blocking - another solution I can think of rn (although it isn't really optimal), is having Auto NONG download a precompiled .exe of yt-dlp on Windows and the equivalent on other platforms. That way it has an up-to-date youtube downloader with frequent fixes and is less likely to get banned off of YouTube's servers.
Generally, I'd be down to host an instance, but considering my previous efforts to get mine unbanned from YouTube have been unsuccessful (partially due to me not having any residential IPs to proxy through), I'll have to say no sadly.

Another solution **(and probably the best as of right now)** would be to download submitted YouTube videos as mp3 when they get merged (could be done using GitHub actions) and have them hosted somewhere for the mod to simply download directly. Something like this could even be integrated into my [sfh-mirror](https://github.com/RoootTheFox/sfh-mirror) project, repurposing it to a glorified SFH *and* YouTube mirror. Existing songs could be downloaded in bulk too. This is probably the simplest and most realistic solution.

Pinging @FlafyDev for further ideas ^^

**Comment by FlafyDev** [comment]
> > Well ive did read some issues and cobalt is gonna drop supporting apis. We need to host our own runner? Any ideas for this @RoootTheFox
> 
> I am hosting my own cobalt instance atm, although it is constantly blocked from accessing YouTube due to its anti-bot IP blocking - another solution I can think of rn (although it isn't really optimal), is having Auto NONG download a precompiled .exe of yt-dlp on Windows and the equivalent on other platforms. That way it has an up-to-date youtube downloader with frequent fixes and is less likely to get banned off of YouTube's servers. Generally, I'd be down to host an instance, but considering my previous efforts to get mine unbanned from YouTube have been unsuccessful (partially due to me not having any residential IPs to proxy through), I'll have to say no sadly.
> 

I thought about embedding yt-dlp into the mod but it's not possible to run an executable like that in Android. I think it'd be possible to run it by embedding a Python Interpreter in the cpp project and running the yt-dlp project (which is written in Python) that way. But yeah the situation with Youtube downloading rn is bad and I don't want users to get banned after a few days of downloading NONGs. Though yt-dlp has a lot of other services, like SoundCloud, so that might be worth exploring... 

Thank you for offering to use your server for songs, though! It's sad to see the state of YT downloading


> Another solution **(and probably the best as of right now)** would be to download submitted YouTube videos as mp3 when they get merged (could be done using GitHub actions) and have them hosted somewhere for the mod to simply download directly. Something like this could even be integrated into my [sfh-mirror](https://github.com/RoootTheFox/sfh-mirror) project, repurposing it to a glorified SFH _and_ YouTube mirror. Existing songs could be downloaded in bulk too. This is probably the simplest and most realistic solution.
> 
> Pinging @FlafyDev for further ideas ^^

So that will basically be a service similar to SFH. Where users submit songs and then someone hosts the accepted submissions.
That does have the caveat of not allow users to download Youtube songs from in game and easily test their submissions before submitting, but I don't think it's a big issue. It prevents using any songs unless it is located locally or has been submitted. 
I am a bit concerned about the legality of it(hosting and directly distributing copyrighted music), and if we already have SFH doing the same thing, I don't think having a similar service under a different name will bring much value. Correct me if I'm wrong, though


Currently the accepted submissions for Auto Nong's index are moving to SFH. I'm not sure what to try next other than leeching off of a different service in yt-dlp

**Comment by larziwau** [comment]
well why we use alot of different servers? why we wont merge them to only one server? we can store the songs in root's mirror (if they allow too =3)

also we can make a github action to check if the songs in database still exist and remove deleted or unused ones to save space maybe?

**Comment by larziwau** [comment]
> Another solution **(and probably the best as of right now)** would be to download submitted YouTube videos as mp3 when they get merged (could be done using GitHub actions) and have them hosted somewhere for the mod to simply download directly. Something like this could even be integrated into my [sfh-mirror](https://github.com/RoootTheFox/sfh-mirror) project, repurposing it to a glorified SFH _and_ YouTube mirror. Existing songs could be downloaded in bulk too. This is probably the simplest and most realistic solution.

also, why we update the lists so regularly and not use diff patches like ublockorigin? im unsure if we can do that tho, btw we can continue this chat in discord if yall want

**Pull request closed without merging**
